#!/bin/sh

set -eu

ARCH=$(uname -m)

echo "Installing package dependencies..."
echo "---------------------------------------------------------------"
pacman -Syu --noconfirm \
	avahi               \
	boost               \
	clang               \
	cmake               \
	eigen               \
	extra-cmake-modules \
	glslang             \
	glib2-devel         \
	kcoreaddons         \
	ki18n               \
	kirigami            \
	kirigami-addons     \
	libarchive          \
	libbsd              \
	libnotify           \
	ninja               \
	nlohmann-json       \
	pipewire            \
	pipewire-audio      \
	pipewire-jack       \
	polkit              \
	python              \
	qcoro               \
	qqc2-desktop-style  \
	qt6-declarative     \
	qt6-tools           \
	rust                \
	shaderc             \
	spirv-tools         \
	vulkan-headers

echo "Installing debloated packages..."
echo "---------------------------------------------------------------"
get-debloated-pkgs --add-common --prefer-nano ffmpeg-mini kiconthemes-mini

# Comment this out if you need an AUR package
#make-aur-package PACKAGENAME

echo "Building xrizer..."
echo "---------------------------------------------------------------"
git clone https://github.com/Supreeeme/xrizer.git ./xrizer && (
	cd ./xrizer

	# Same pinned commit as the WiVRn flatpak
	git checkout be664bb93eebdd82336d00230154bacc6f8b9765

	cargo xbuild --release

	# cp -L is required, the vrclient.so symlinks generated by
	# 'cargo xbuild' are broken as they point into target/
	mkdir -p ./xrizer-runtime
	cp -L ./target/release/libxrizer.so ./xrizer-runtime
	cp -rL ./target/release/bin ./xrizer-runtime
)
mkdir -p /usr/lib/xrizer
cp -ra ./xrizer/xrizer-runtime/. /usr/lib/xrizer

echo "Building WiVRn..."
echo "---------------------------------------------------------------"
git clone https://github.com/WiVRn/WiVRn.git ./WiVRn && (
	cd ./WiVRn

	# Build the latest stable tag
	TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
	git checkout "$TAG"
	VERSION="${TAG#v}"
	echo "$VERSION" > ~/version

	patch -p1 < ../patches/0001-active_runtime.cpp-look-up-manifest-and-xrizer-relative-to-the-executable.patch
	patch -p1 < ../patches/0002-wivrn_server.cpp-detect-relocatable-xrizer.patch

	cmake -B ./build . -GNinja -Wno-dev \
		-DCMAKE_BUILD_TYPE=Release              \
		-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
		-DCMAKE_INSTALL_PREFIX=/usr             \
		-DWIVRN_BUILD_CLIENT=OFF                \
		-DWIVRN_BUILD_SERVER=ON                 \
		-DWIVRN_BUILD_DASHBOARD=ON              \
		-DWIVRN_BUILD_WIVRNCTL=ON               \
		-DWIVRN_USE_SYSTEM_BOOST=ON             \
		-DWIVRN_USE_VAAPI=ON                    \
		-DWIVRN_USE_X264=ON                     \
		-DWIVRN_USE_NVENC=ON                    \
		-DWIVRN_USE_VULKAN_ENCODE=ON            \
		-DWIVRN_USE_PIPEWIRE=ON                 \
		-DWIVRN_USE_PULSEAUDIO=ON               \
		-DWIVRN_FEATURE_SOLARXR=ON              \
		-DWIVRN_FEATURE_STEAMVR_LIGHTHOUSE=ON   \
		-DWIVRN_OPENXR_MANIFEST_TYPE=relative   \
		-DOVR_COMPAT_SEARCH_PATH=/opt/xrizer:/opt/opencomposite:/opt/VapoR
	cmake --build ./build
	cmake --install ./build
)
